comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        only_pulls: true
