name: Coverage

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.x
      - name: Collect coverage
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm run cov:check
      - name: Submit core report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
